export type MaisonCortesLocale = 'fr' | 'en' | 'it' | 'de';

const defaultLocale: MaisonCortesLocale = 'fr';
export const maisonCortesContactEmail = 'registry@maisoncortes.ch';

export const maisonCortesCopy = {
  brandTop: 'MAISON',
  brandBottom: 'C O R T E S',
  contactEmail: maisonCortesContactEmail,
  defaultLocale,
  locales: {
    fr: {
      cta: 'Acquerir',
      selectionAction: 'Ajouter a la selection',
      navCatalogue: 'Catalogue',
      navContact: 'Contact',
      navSelection: 'Selection',
      catalogueTitle: 'Catalogue',
      catalogueDescription: 'Objets classes par ville.',
      contactPageTitle: 'Contact',
      contactPageDescription: 'Contact direct pour Maison Cortes.',
      objectListTitle: 'Objets',
      cityAvailabilityLabel: 'Disponibles',
      footerContactTitle: 'Contact',
      footerLegalTitle: 'Mentions legales',
      legalLines: ['Maison Cortes Sarl', 'Lausanne, Suisse', 'IDE / TVA communique sur facture'],
      returnsTitle: 'Retours et garantie',
      returnsBody: 'Retours sous 14 jours si non portes. Ecrire avant renvoi.',
      materialsTitle: 'Materiaux et disclosure',
      materialsBody: 'Base argent 925. Surface plaquee or. Pierres: diamants de laboratoire. Eviter abrasion et produits chimiques.',
      shippingLine: 'Expedition Suisse 2-4 jours ouvrables via service assure.',
      currencyNote: 'Prix en CHF. Expedition Suisse uniquement.',
      languageTitle: 'Langue',
      labDisclosureShort: 'Diamants de laboratoire, base argent 925, surface plaquee or.',
      confirmationTitle: 'Confirmation',
      confirmationLead: 'Nous conservons votre selection et envoyons une confirmation detaillee.',
      confirmationNext: ['Livraison Suisse 2-4 jours ouvrables.', 'Retours sous 14 jours si non portes.', `Contact: ${maisonCortesContactEmail}`],
      cancelledTitle: 'Paiement interrompu',
      cancelledLead: 'Aucune transaction en cours. Votre selection reste ouverte.',
      careLine: 'Eviter eau, parfums, abrasion. Essuyer apres port.',
      selectionTitle: 'Selection',
      selectionLead: 'Objet retenu pour vous pendant 24h.',
      selectionEmpty: 'Aucune selection enregistre.',
      selectionPrimary: 'Proceder au paiement',
      selectionRemove: 'Supprimer la selection',
      selectionBack: 'Retour au catalogue',
      selectionUnavailable: 'Selection non disponible. Choisir un autre objet.',
      selectionHold: 'Reservation active ~{minutes} minutes.',
      statusLabels: { available: 'Disponible', reserved: 'Reserve', sold: 'Vendu', archived: 'Archive' },
      statusUnavailable: 'Objet non disponible.',
      editionLabel: 'Edition',
    },
    en: {
      cta: 'Acquire',
      selectionAction: 'Add to selection',
      navCatalogue: 'Catalogue',
      navContact: 'Contact',
      navSelection: 'Selection',
      catalogueTitle: 'Catalogue',
      catalogueDescription: 'Objects organized by city.',
      contactPageTitle: 'Contact',
      contactPageDescription: 'Direct contact for Maison Cortes.',
      objectListTitle: 'Objects',
      cityAvailabilityLabel: 'Available',
      footerContactTitle: 'Contact',
      footerLegalTitle: 'Legal',
      legalLines: ['Maison Cortes Sarl', 'Lausanne, Switzerland', 'Company ID / VAT on invoice'],
      returnsTitle: 'Returns & warranty',
      returnsBody: '14-day returns if unworn. Email before sending anything back.',
      materialsTitle: 'Materials & disclosure',
      materialsBody: '925 sterling silver base. Gold-plated surface. Stones: lab-grown diamonds. Avoid abrasion and chemicals.',
      shippingLine: 'Switzerland shipping only, 2-4 business days, insured service.',
      currencyNote: 'Pricing in CHF. Shipping Switzerland only.',
      languageTitle: 'Language',
      labDisclosureShort: 'Lab-grown diamonds, 925 base, gold-plated surface.',
      confirmationTitle: 'Confirmation',
      confirmationLead: 'We recorded your selection and will follow up with a detailed confirmation.',
      confirmationNext: ['Delivery: Switzerland, 2-4 business days.', 'Returns within 14 days if unworn.', `Contact: ${maisonCortesContactEmail}`],
      cancelledTitle: 'Payment interrupted',
      cancelledLead: 'No charge made. Your selection remains open.',
      careLine: 'Avoid water, fragrance, abrasion. Wipe after wear.',
      selectionTitle: 'Selection',
      selectionLead: 'We hold this object for you for 24h.',
      selectionEmpty: 'No selection saved.',
      selectionPrimary: 'Proceed to checkout',
      selectionRemove: 'Remove selection',
      selectionBack: 'Back to catalogue',
      selectionUnavailable: 'Selection unavailable. Choose another object.',
      selectionHold: 'Reservation active for ~{minutes} minutes.',
      statusLabels: { available: 'Available', reserved: 'Reserved', sold: 'Sold', archived: 'Archived' },
      statusUnavailable: 'Object not available.',
      editionLabel: 'Edition',
    },
    it: {
      cta: 'Acquistare',
      selectionAction: 'Aggiungi alla selezione',
      navCatalogue: 'Catalogo',
      navContact: 'Contatto',
      navSelection: 'Selezione',
      catalogueTitle: 'Catalogo',
      catalogueDescription: 'Oggetti organizzati per citta.',
      contactPageTitle: 'Contatto',
      contactPageDescription: 'Contatto diretto per Maison Cortes.',
      objectListTitle: 'Oggetti',
      cityAvailabilityLabel: 'Disponibili',
      footerContactTitle: 'Contatto',
      footerLegalTitle: 'Note legali',
      legalLines: ['Maison Cortes Sarl', 'Losanna, Svizzera', 'ID azienda / IVA su fattura'],
      returnsTitle: 'Resi e garanzia',
      returnsBody: 'Reso entro 14 giorni se non indossato. Scrivere prima di spedire.',
      materialsTitle: 'Materiali e disclosure',
      materialsBody: 'Base argento 925. Superficie placcata oro. Pietre: diamanti di laboratorio. Evitare abrasione e chimici.',
      shippingLine: 'Spedizione solo Svizzera, 2-4 giorni lavorativi, servizio assicurato.',
      currencyNote: 'Prezzi in CHF. Spedizione solo Svizzera.',
      languageTitle: 'Lingua',
      labDisclosureShort: 'Diamanti di laboratorio, base argento 925, superficie placcata oro.',
      confirmationTitle: 'Conferma',
      confirmationLead: 'Abbiamo registrato la selezione e invieremo una conferma dettagliata.',
      confirmationNext: ['Consegna: Svizzera, 2-4 giorni lavorativi.', 'Resi entro 14 giorni se non indossato.', `Contatto: ${maisonCortesContactEmail}`],
      cancelledTitle: 'Pagamento interrotto',
      cancelledLead: 'Nessun addebito eseguito. La selezione resta aperta.',
      careLine: 'Evitare acqua, profumi, abrasione. Pulire dopo l uso.',
      selectionTitle: 'Selezione',
      selectionLead: 'Oggetto mantenuto per 24h.',
      selectionEmpty: 'Nessuna selezione salvata.',
      selectionPrimary: 'Procedi al pagamento',
      selectionRemove: 'Rimuovi selezione',
      selectionBack: 'Torna al catalogo',
      selectionUnavailable: 'Selezione non disponibile. Scegli un altro oggetto.',
      selectionHold: 'Prenotazione attiva per ~{minutes} minuti.',
      statusLabels: { available: 'Disponibile', reserved: 'Riservato', sold: 'Venduto', archived: 'Archivio' },
      statusUnavailable: 'Oggetto non disponibile.',
      editionLabel: 'Edizione',
    },
    de: {
      cta: 'Erwerben',
      selectionAction: 'Zur Auswahl hinzufügen',
      navCatalogue: 'Katalog',
      navContact: 'Kontakt',
      navSelection: 'Auswahl',
      catalogueTitle: 'Katalog',
      catalogueDescription: 'Objekte nach Stadt geordnet.',
      contactPageTitle: 'Kontakt',
      contactPageDescription: 'Direkter Kontakt für Maison Cortes.',
      objectListTitle: 'Objekte',
      cityAvailabilityLabel: 'Verfügbar',
      footerContactTitle: 'Kontakt',
      footerLegalTitle: 'Rechtliches',
      legalLines: ['Maison Cortes Sarl', 'Lausanne, Schweiz', 'UID / MwSt. auf der Rechnung'],
      returnsTitle: 'Rückgabe & Garantie',
      returnsBody: 'Rückgabe innerhalb 14 Tagen, wenn ungetragen. Bitte vorher schreiben.',
      materialsTitle: 'Materialien & Disclosure',
      materialsBody: '925 Silberbasis. Vergoldete Oberfläche. Steine: Labordiamanten. Abrieb und Chemie vermeiden.',
      shippingLine: 'Versand nur Schweiz, 2–4 Werktage, versicherter Service.',
      currencyNote: 'Preise in CHF. Versand nur Schweiz.',
      languageTitle: 'Sprache',
      labDisclosureShort: 'Labordiamanten, 925-Basis, vergoldete Oberfläche.',
      confirmationTitle: 'Bestätigung',
      confirmationLead: 'Wir haben Ihre Auswahl gespeichert und senden eine detaillierte Bestätigung.',
      confirmationNext: ['Lieferung: Schweiz, 2–4 Werktage.', 'Rückgabe innerhalb 14 Tage, wenn ungetragen.', `Kontakt: ${maisonCortesContactEmail}`],
      cancelledTitle: 'Zahlung abgebrochen',
      cancelledLead: 'Keine Belastung erfolgt. Ihre Auswahl bleibt offen.',
      careLine: 'Kein Wasser, kein Parfum, Abrieb vermeiden. Nach dem Tragen abwischen.',
      selectionTitle: 'Auswahl',
      selectionLead: 'Objekt 24h für Sie reserviert.',
      selectionEmpty: 'Keine Auswahl gespeichert.',
      selectionPrimary: 'Zur Kasse',
      selectionRemove: 'Auswahl entfernen',
      selectionBack: 'Zurück zum Katalog',
      selectionUnavailable: 'Auswahl nicht verfügbar. Bitte anderes Objekt wählen.',
      selectionHold: 'Reservierung aktiv für ~{minutes} Minuten.',
      statusLabels: { available: 'Verfügbar', reserved: 'Reserviert', sold: 'Verkauft', archived: 'Archiv' },
      statusUnavailable: 'Objekt nicht verfügbar.',
      editionLabel: 'Edition',
    },
  },
};

export function resolveMaisonCortesLocale(raw?: string | null): MaisonCortesLocale {
  if (raw === 'fr' || raw === 'en' || raw === 'it' || raw === 'de') return raw;
  return defaultLocale;
}
