export type MaisonCortesProduct = {
  id: string;
  city: 'LUGANO' | 'GENEVE' | 'ZURICH' | 'LAUSANNE' | 'ZERMATT';
  citySlug: 'lugano' | 'geneve' | 'zurich' | 'lausanne' | 'zermatt';
  object: string;
  index: string;
  objectSlug: string;
  specs: string[];
  priceChf: number;
  status: 'available' | 'reserved' | 'sold' | 'archived';
  editionSize?: number;
};

export const maisonCortesProducts: MaisonCortesProduct[] = [
  {
    id: 'lugano-bracelet-02',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'BRACELET',
    index: '02',
    objectSlug: 'bracelet-02',
    specs: ['Sterling silver (925).', 'Gold-plated surface.', '318 diamonds.', 'Width 7 mm.'],
    priceChf: 530,
    status: 'available',
    editionSize: 87,
  },
  {
    id: 'lugano-chain-01',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'CHAIN',
    index: '01',
    objectSlug: 'chain-01',
    specs: ['Sterling silver base.', 'Gold-plated links.', 'Hand-set zircon.', 'Length 48 cm.'],
    priceChf: 480,
    status: 'available',
    editionSize: 120,
  },
  {
    id: 'lugano-ring-03',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'RING',
    index: '03',
    objectSlug: 'ring-03',
    specs: ['Sterling silver (925).', 'Square-cut zircon.', 'Channel setting.', 'Width 5 mm.'],
    priceChf: 360,
    status: 'available',
    editionSize: 140,
  },
  {
    id: 'lugano-ring-04',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'RING',
    index: '04',
    objectSlug: 'ring-04',
    specs: ['Sterling silver (925).', 'Princess-cut zircon.', 'Gold-plated surface.', 'Tapered shoulders.'],
    priceChf: 380,
    status: 'available',
    editionSize: 96,
  },
  {
    id: 'lugano-ring-05',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'RING',
    index: '05',
    objectSlug: 'ring-05',
    specs: ['White gold-plated surface.', 'Lab-grown diamond pave.', 'Comfort fit.', 'Width 4 mm.'],
    priceChf: 410,
    status: 'available',
    editionSize: 88,
  },
  {
    id: 'lugano-watch-01',
    city: 'LUGANO',
    citySlug: 'lugano',
    object: 'WATCH',
    index: '01',
    objectSlug: 'watch-01',
    specs: ['Stainless steel case.', 'Moissanite bezel.', 'Quartz movement.', 'Case 40 mm.'],
    priceChf: 1120,
    status: 'available',
    editionSize: 42,
  },
  {
    id: 'geneve-pendant-03',
    city: 'GENEVE',
    citySlug: 'geneve',
    object: 'PENDANT',
    index: '03',
    objectSlug: 'pendant-03',
    specs: ['Medical-grade titanium core.', 'Gold-plated surface.', '176 diamonds.', 'Length 28 mm.'],
    priceChf: 610,
    status: 'available',
    editionSize: 64,
  },
  {
    id: 'geneve-chain-01',
    city: 'GENEVE',
    citySlug: 'geneve',
    object: 'CHAIN',
    index: '01',
    objectSlug: 'chain-01',
    specs: ['Gold-plated clasp.', 'Sterling silver links.', 'Tennis setting.', 'Length 45 cm.'],
    priceChf: 520,
    status: 'available',
    editionSize: 110,
  },
  {
    id: 'geneve-ring-02',
    city: 'GENEVE',
    citySlug: 'geneve',
    object: 'RING',
    index: '02',
    objectSlug: 'ring-02',
    specs: ['Tungsten core.', 'Gold-plated surface.', 'Beveled edges.', 'Width 8 mm.'],
    priceChf: 540,
    status: 'available',
    editionSize: 78,
  },
  {
    id: 'zurich-ring-01',
    city: 'ZURICH',
    citySlug: 'zurich',
    object: 'RING',
    index: '01',
    objectSlug: 'ring-01',
    specs: ['Stainless steel frame.', 'Gold-plated surface.', 'Laser-etched serial number.', 'Width 5 mm.'],
    priceChf: 340,
    status: 'available',
    editionSize: 120,
  },
  {
    id: 'zurich-ring-02',
    city: 'ZURICH',
    citySlug: 'zurich',
    object: 'RING',
    index: '02',
    objectSlug: 'ring-02',
    specs: ['Three-stone setting.', 'Lab-grown diamonds.', 'Sterling silver (925).', 'Width 4 mm.'],
    priceChf: 360,
    status: 'available',
    editionSize: 90,
  },
  {
    id: 'zurich-earrings-02',
    city: 'ZURICH',
    citySlug: 'zurich',
    object: 'EARRINGS',
    index: '02',
    objectSlug: 'earrings-02',
    specs: ['Sterling silver hoops.', 'Gold-plated surface.', 'Lab-grown diamonds.', 'Diameter 18 mm.'],
    priceChf: 420,
    status: 'available',
    editionSize: 75,
  },
  {
    id: 'zurich-chain-02',
    city: 'ZURICH',
    citySlug: 'zurich',
    object: 'CHAIN',
    index: '02',
    objectSlug: 'chain-02',
    specs: ['Sterling silver base.', 'Gold-plated prong links.', '5 mm stones.', 'Length 50 cm.'],
    priceChf: 450,
    status: 'available',
    editionSize: 130,
  },
  {
    id: 'lausanne-bracelet-01',
    city: 'LAUSANNE',
    citySlug: 'lausanne',
    object: 'BRACELET',
    index: '01',
    objectSlug: 'bracelet-01',
    specs: ['Sterling silver (925).', 'Brushed finish.', '84 diamonds.', 'Width 6 mm.'],
    priceChf: 420,
    status: 'available',
    editionSize: 58,
  },
  {
    id: 'lausanne-ring-02',
    city: 'LAUSANNE',
    citySlug: 'lausanne',
    object: 'RING',
    index: '02',
    objectSlug: 'ring-02',
    specs: ['Sterling silver (925).', 'Gold-plated surface.', 'Gradated stones.', 'Width 5 mm.'],
    priceChf: 460,
    status: 'available',
    editionSize: 92,
  },
  {
    id: 'zermatt-watch-01',
    city: 'ZERMATT',
    citySlug: 'zermatt',
    object: 'WATCH',
    index: '01',
    objectSlug: 'watch-01',
    specs: ['Stainless steel case.', 'Satin black dial.', '66 diamonds.', 'Case 34 mm.'],
    priceChf: 980,
    status: 'available',
    editionSize: 42,
  },
  {
    id: 'zermatt-ring-02',
    city: 'ZERMATT',
    citySlug: 'zermatt',
    object: 'RING',
    index: '02',
    objectSlug: 'ring-02',
    specs: ['Matching pair.', 'Gold-plated stainless steel.', 'Two-tone finish.', 'Width 6 mm.'],
    priceChf: 520,
    status: 'available',
    editionSize: 70,
  },
];

export const maisonCortesCities = Array.from(
  new Map(maisonCortesProducts.map((product) => [product.citySlug, { name: product.city, slug: product.citySlug }])).values()
);
